apiVersion: v1
kind: Service
metadata:
  name: evnt-rcvr
spec:
  type: NodePort
  selector:
    app: evnt-rcvr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30036
